/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.CdcAdminRole;

import business.EcoSystem;
import business.enterprise.CdcEnterprise;
import business.enterprise.Enterprise;
import business.network.Network;
import business.userAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Smeet
 */
public class CdcWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CdcWorkAreaJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
   // CdcEnterprise parentEnt;
    UserAccount userAccount;
    EcoSystem system;
    Network network;
    public CdcWorkAreaJPanel(JPanel upc, Enterprise enterprise, UserAccount ua,EcoSystem system,Network n) {
        initComponents();
        this.userProcessContainer = upc;
        this.enterprise = enterprise;
        this.userAccount = ua;
        this.system = system;
        this.network = n;
        System.out.println("s,meet");
        System.out.println(enterprise.getName());
        System.out.println("kothari");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageStateOrganizationJButton = new javax.swing.JButton();
        manageDistributorOrganizationJButton = new javax.swing.JButton();
        manageManufacturerOrganizationJButton = new javax.swing.JButton();
        viewVaccinesJButton = new javax.swing.JButton();
        approveNewOrdersJButton = new javax.swing.JButton();
        licenceWorkAreaJButton = new javax.swing.JButton();
        manageInsuranceOrganizationJButton = new javax.swing.JButton();
        paymentsJButton = new javax.swing.JButton();
        invoiceJButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setText("        CDC Work Area");

        manageStateOrganizationJButton.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        manageStateOrganizationJButton.setText("Manage State Enterprise");
        manageStateOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageStateOrganizationJButtonActionPerformed(evt);
            }
        });

        manageDistributorOrganizationJButton.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        manageDistributorOrganizationJButton.setText("Manage Distributor Organization");
        manageDistributorOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDistributorOrganizationJButtonActionPerformed(evt);
            }
        });

        manageManufacturerOrganizationJButton.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        manageManufacturerOrganizationJButton.setText("Manage Manufacturer Organization");
        manageManufacturerOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageManufacturerOrganizationJButtonActionPerformed(evt);
            }
        });

        viewVaccinesJButton.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        viewVaccinesJButton.setText("View Vaccines");
        viewVaccinesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewVaccinesJButtonActionPerformed(evt);
            }
        });

        approveNewOrdersJButton.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        approveNewOrdersJButton.setText("Approve New Order");
        approveNewOrdersJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveNewOrdersJButtonActionPerformed(evt);
            }
        });

        licenceWorkAreaJButton.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        licenceWorkAreaJButton.setText("Licence Approval");
        licenceWorkAreaJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenceWorkAreaJButtonActionPerformed(evt);
            }
        });

        manageInsuranceOrganizationJButton.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        manageInsuranceOrganizationJButton.setText("Manage Insurance Organization");
        manageInsuranceOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageInsuranceOrganizationJButtonActionPerformed(evt);
            }
        });

        paymentsJButton.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        paymentsJButton.setText("Payments");
        paymentsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentsJButtonActionPerformed(evt);
            }
        });

        invoiceJButton.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        invoiceJButton.setText("Invoice from Distributor");
        invoiceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(invoiceJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(293, 293, 293)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(81, 81, 81)
                            .addComponent(manageStateOrganizationJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(128, 128, 128)
                            .addComponent(licenceWorkAreaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(81, 81, 81)
                            .addComponent(manageDistributorOrganizationJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(128, 128, 128)
                            .addComponent(viewVaccinesJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(81, 81, 81)
                            .addComponent(manageManufacturerOrganizationJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(128, 128, 128)
                            .addComponent(approveNewOrdersJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(81, 81, 81)
                            .addComponent(manageInsuranceOrganizationJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(128, 128, 128)
                            .addComponent(paymentsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(manageStateOrganizationJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(licenceWorkAreaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageDistributorOrganizationJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(viewVaccinesJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(manageManufacturerOrganizationJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(approveNewOrdersJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageInsuranceOrganizationJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(paymentsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(invoiceJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageStateOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageStateOrganizationJButtonActionPerformed
        // TODO add your handling code here:
        ManageStateEnterpriseJPanel msojp = new ManageStateEnterpriseJPanel(userProcessContainer,
                                                                                enterprise,network,system);
        userProcessContainer.add("ManageStateOrganizationJP", msojp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageStateOrganizationJButtonActionPerformed

    private void manageDistributorOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDistributorOrganizationJButtonActionPerformed
        // TODO add your handling code here:
        ManageDistributorJPanel mdojp = new ManageDistributorJPanel(userProcessContainer,
                                                                    enterprise.getOrganizationDirectory(),
                                                                    enterprise,system);
        userProcessContainer.add("ManageDistributorOrganizationJP", mdojp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageDistributorOrganizationJButtonActionPerformed

    private void manageManufacturerOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageManufacturerOrganizationJButtonActionPerformed
        // TODO add your handling code here:
        ManageManufacturerJPanel mmojp = new ManageManufacturerJPanel(userProcessContainer,
                                                                      enterprise.getOrganizationDirectory(),
                                                                      enterprise);
        userProcessContainer.add("ManageManufacturerOrganizationJP", mmojp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageManufacturerOrganizationJButtonActionPerformed

    private void viewVaccinesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewVaccinesJButtonActionPerformed
        // TODO add your handling code here:
        ViewVaccinesJPanel vvjp = new ViewVaccinesJPanel(userProcessContainer,enterprise);
        userProcessContainer.add("ViewVaccineJP", vvjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewVaccinesJButtonActionPerformed

    private void approveNewOrdersJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveNewOrdersJButtonActionPerformed
        // TODO add your handling code here:
        ApproveOrderFromPhdJPanel aofpjp = new ApproveOrderFromPhdJPanel(userProcessContainer,
                                                                        userAccount,enterprise);
        userProcessContainer.add("approveOrderFromPhdJP", aofpjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_approveNewOrdersJButtonActionPerformed

    private void licenceWorkAreaJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenceWorkAreaJButtonActionPerformed
        // TODO add your handling code here:
        LicenceApprovalWorkAreaJPanel lawajp = new LicenceApprovalWorkAreaJPanel(userProcessContainer,enterprise,userAccount);
        userProcessContainer.add("LicenceApproveWAJP", lawajp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_licenceWorkAreaJButtonActionPerformed

    private void manageInsuranceOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageInsuranceOrganizationJButtonActionPerformed
        // TODO add your handling code here:
        ManageInsuranceJPanel mijp = new ManageInsuranceJPanel(userProcessContainer, enterprise,userAccount);
        userProcessContainer.add("ManageInsurance", mijp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageInsuranceOrganizationJButtonActionPerformed

    private void paymentsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentsJButtonActionPerformed
        // TODO add your handling code here:
        MakePaymentsJPanel mpjp = new MakePaymentsJPanel(userProcessContainer,userAccount,enterprise);
        userProcessContainer.add("MakePaymentsJP", mpjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_paymentsJButtonActionPerformed

    private void invoiceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceJButtonActionPerformed
        // TODO add your handling code here:
        InvoicefromDistributorJPanel idjp = new InvoicefromDistributorJPanel(userProcessContainer, userAccount,enterprise);
        userProcessContainer.add("MakeInvoicePaymentJP", idjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_invoiceJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveNewOrdersJButton;
    private javax.swing.JButton invoiceJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton licenceWorkAreaJButton;
    private javax.swing.JButton manageDistributorOrganizationJButton;
    private javax.swing.JButton manageInsuranceOrganizationJButton;
    private javax.swing.JButton manageManufacturerOrganizationJButton;
    private javax.swing.JButton manageStateOrganizationJButton;
    private javax.swing.JButton paymentsJButton;
    private javax.swing.JButton viewVaccinesJButton;
    // End of variables declaration//GEN-END:variables
}
