/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.CdcAdminRole;

import business.enterprise.Enterprise;
import business.userAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Smeet
 */
public class LicenceApprovalWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LicenceApprovalWOrkAreaJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    UserAccount ua;
    public LicenceApprovalWorkAreaJPanel(JPanel upc, Enterprise e,UserAccount ua) {
        initComponents();
        this.userProcessContainer = upc;
        this.enterprise = e;
        this.ua = ua;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        forClinicJButton = new javax.swing.JButton();
        forHospitalJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        forClinicJButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        forClinicJButton.setText("For Clinic");
        forClinicJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forClinicJButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 123;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 294, 473, 333);
        add(forClinicJButton, gridBagConstraints);

        forHospitalJButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        forHospitalJButton.setText("For Hospital");
        forHospitalJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forHospitalJButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 105;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(68, 294, 0, 333);
        add(forHospitalJButton, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setText("  Licence Work Area");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(66, 307, 0, 0);
        add(jLabel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void forHospitalJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forHospitalJButtonActionPerformed
        // TODO add your handling code here:
        approveLicenceforHospitalJPanel aljp = new approveLicenceforHospitalJPanel(userProcessContainer, enterprise,ua);
        userProcessContainer.add("approveLicenceJP", aljp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_forHospitalJButtonActionPerformed

    private void forClinicJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forClinicJButtonActionPerformed
        // TODO add your handling code here:
        LicenceForClinicJPanel lfcjp = new LicenceForClinicJPanel(userProcessContainer,enterprise,ua);
        userProcessContainer.add("licenceforClinicJP", lfcjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_forClinicJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton forClinicJButton;
    private javax.swing.JButton forHospitalJButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
