/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.warehouseRole;

import business.enterprise.Enterprise;
import business.enterprise.PhdEnterprise;
import business.organization.WarehouseOrganization;
import business.userAccount.UserAccount;
import business.workQueue.OrderRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Smeet
 */
public class WarehouseWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form WarehouseWorkAreaJPanel
     */
    JPanel userProcessContainer;
    WarehouseOrganization organization;
    UserAccount userAccount;
    Enterprise enterprise;
    
    public WarehouseWorkAreaJPanel(JPanel upc,WarehouseOrganization o,UserAccount ua,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = upc;
        this.organization = o;
        this.userAccount = ua;
        this.enterprise = enterprise;
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        inventoryJButton = new javax.swing.JButton();
        viewOrdersJButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel1.setText("     Warehouse Work Area");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 54;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(56, 299, 0, 309);
        add(jLabel1, gridBagConstraints);

        inventoryJButton.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        inventoryJButton.setText("Manage Inventory");
        inventoryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryJButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 41;
        gridBagConstraints.ipady = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(84, 331, 0, 0);
        add(inventoryJButton, gridBagConstraints);

        viewOrdersJButton.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        viewOrdersJButton.setText("View Orders");
        viewOrdersJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrdersJButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 77;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(55, 331, 446, 0);
        add(viewOrdersJButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void inventoryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryJButtonActionPerformed
        // TODO add your handling code here:
        ManageWarehouseInventoryJPanel mijp = new ManageWarehouseInventoryJPanel(userProcessContainer, organization,userAccount,enterprise);
        userProcessContainer.add("ManageInventoryJP", mijp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_inventoryJButtonActionPerformed

    private void viewOrdersJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrdersJButtonActionPerformed
        // TODO add your handling code here:
        ViewOrdersJPanel vojp = new ViewOrdersJPanel(userProcessContainer,organization,userAccount);
        userProcessContainer.add("ViewOrdersJP", vojp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewOrdersJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inventoryJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton viewOrdersJButton;
    // End of variables declaration//GEN-END:variables
}
