/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.insuranceRole;

import business.enterprise.CdcEnterprise;
import business.enterprise.Enterprise;
import business.organization.InsuranceOrganization;
import business.organization.Organization;
import business.patient.Patient;
import business.userAccount.UserAccount;
import business.workQueue.PaymentRequest;
import business.workQueue.WorkRequest;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Smeet
 */
public class InsurancePaymentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InsurancePaymentJPanel
     */
    JPanel userProcessContainer;
    InsuranceOrganization organization;
    UserAccount userAccount;
    Enterprise enterprise;
    CdcEnterprise parentEnt;

    public InsurancePaymentJPanel(JPanel upc, InsuranceOrganization organization, UserAccount ua, Enterprise e, CdcEnterprise parentEnt) {
        initComponents();
        this.userProcessContainer = upc;
        this.organization = organization;
        this.userAccount = ua;
        this.enterprise = e;
        this.parentEnt = parentEnt;
        populatePaymentTable();
    }

    private void populatePaymentTable() {
        DefaultTableModel dtm = (DefaultTableModel) paymentJTable.getModel();
        dtm.setRowCount(0);

        for (WorkRequest wr : organization.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof PaymentRequest) {
                PaymentRequest pr = (PaymentRequest) wr;
                Object row[] = new Object[7];
                row[0] = pr;
                row[1] = pr.getStatus();
                row[2] = pr.getSender();
                row[3] = pr.getVaccine().getVacName();
                row[4] = pr.getVaccine().getPrice();
                row[5] = pr.getVaccine().getQuantity();
                row[6] = pr.getResult();
                dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        paymentJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        paymentJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Sender", "Status", "Payment Request", "Vaccine Name", "Price", "Quantity", "Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(paymentJTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 574;
        gridBagConstraints.ipady = 72;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(64, 123, 0, 135);
        add(jScrollPane1, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel1.setText("      Incoming Payment");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(66, 311, 0, 0);
        add(jLabel1, gridBagConstraints);

        jButton1.setText("Make Payment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.ipady = 31;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(56, 342, 433, 0);
        add(jButton1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PaymentRequest pr;
        int selectedRow = paymentJTable.getSelectedRow();
        pr = (PaymentRequest) paymentJTable.getValueAt(selectedRow, 0);

        pr.setSender(userAccount);
        pr.setStatus("Paid");

        pr.setResult("Processed");
        populatePaymentTable();

//        Organization foundOrg = null;
//        for (Organization o : parentEnt.getOrganizationDirectory().getOrganizationList()) {
//            if (o instanceof InsuranceOrganization) {
//                for (Patient p : parentEnt.getPatientList()) {
//                    if (p.getInsuranceStatus().equals("Insured")) {
//                        pr.setStatus("Paid");
//                    } else {
//                        foundOrg = o;
//                        break;
//                    }
//                    if (foundOrg != null) {
//                        foundOrg.getWorkQueue().getWorkRequestList().add(pr);
//                        userAccount.getWorkQueue().getWorkRequestList().add(pr);
//                        populatePaymentTable();
//                    }
//                }
//            }
//        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable paymentJTable;
    // End of variables declaration//GEN-END:variables
}
