/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.insuranceRole;

import business.enterprise.CdcEnterprise;
import business.enterprise.Enterprise;
import business.organization.InsuranceOrganization;
import business.patient.Patient;
import business.userAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Smeet
 */
public class InsuranceWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form InsuranceWorkArea
     */
    JPanel userProcessContainer;
    InsuranceOrganization organization;
    Enterprise enterprise;
    UserAccount userAccount;
    CdcEnterprise parentEnt;
    Patient patient;
    public InsuranceWorkArea(JPanel upc,InsuranceOrganization io,CdcEnterprise pEnt,UserAccount ua,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = upc;
        this.organization = io;
        this.enterprise = enterprise;
        this.userAccount = ua;
        this.enterprise = pEnt;
        this.patient = new Patient();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        insuranceDetailsJButton = new javax.swing.JButton();
        paymentsJButton = new javax.swing.JButton();

        jLabel1.setText("   Insurance Work Area");

        insuranceDetailsJButton.setText("Insurance Details");
        insuranceDetailsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuranceDetailsJButtonActionPerformed(evt);
            }
        });

        paymentsJButton.setText("Payments");
        paymentsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentsJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(insuranceDetailsJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(paymentsJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(391, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(insuranceDetailsJButton)
                .addGap(58, 58, 58)
                .addComponent(paymentsJButton)
                .addContainerGap(547, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void insuranceDetailsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuranceDetailsJButtonActionPerformed
        // TODO add your handling code here:
        InsuranceDetailsJPanel idjp = new InsuranceDetailsJPanel(userProcessContainer,organization,parentEnt,patient);
        userProcessContainer.add("InsuranceDetails", idjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_insuranceDetailsJButtonActionPerformed

    private void paymentsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentsJButtonActionPerformed
        // TODO add your handling code here:
        InsurancePaymentJPanel ipjp = new InsurancePaymentJPanel(userProcessContainer,organization,userAccount, enterprise,parentEnt);
        userProcessContainer.add("InsurancePayment", ipjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_paymentsJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton insuranceDetailsJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton paymentsJButton;
    // End of variables declaration//GEN-END:variables
}
