/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.distributorRole;

import business.enterprise.Enterprise;
import business.network.Network;
import business.organization.DistributorOrganization;
import business.userAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Smeet
 */
public class DistributorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DistributorWorkAreaJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    DistributorOrganization organization;
    UserAccount userAccount;
    Network network;
    public DistributorWorkAreaJPanel(JPanel upc,Enterprise e,DistributorOrganization organization,UserAccount ua,Network n) {
        initComponents();
        this.userProcessContainer = upc;
        this.enterprise = e;
        this.organization = organization;
        this.userAccount = ua;
        this.network = n;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageWarehouseJButton = new javax.swing.JButton();
        orderApprovalJButton = new javax.swing.JButton();
        PlaceOrderJButton = new javax.swing.JButton();
        paymentsJButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel1.setText("         Distributor Work Area");

        manageWarehouseJButton.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        manageWarehouseJButton.setText("Manage Warehouse");
        manageWarehouseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageWarehouseJButtonActionPerformed(evt);
            }
        });

        orderApprovalJButton.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        orderApprovalJButton.setText("Order Approval");
        orderApprovalJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderApprovalJButtonActionPerformed(evt);
            }
        });

        PlaceOrderJButton.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        PlaceOrderJButton.setText("Place Order");
        PlaceOrderJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaceOrderJButtonActionPerformed(evt);
            }
        });

        paymentsJButton.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        paymentsJButton.setText("Payments");
        paymentsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentsJButtonActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jButton1.setText("Invoice To CDC");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageWarehouseJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(PlaceOrderJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orderApprovalJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(166, 166, 166))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageWarehouseJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderApprovalJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlaceOrderJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(392, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageWarehouseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageWarehouseJButtonActionPerformed
        // TODO add your handling code here:
        ManageWarehouseJPanel mwjp = new ManageWarehouseJPanel(userProcessContainer,organization,enterprise);
        userProcessContainer.add("ManageWarehouseJPanel", mwjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageWarehouseJButtonActionPerformed

    private void orderApprovalJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderApprovalJButtonActionPerformed
        // TODO add your handling code here:
        OrderApprovalFromCdcJPanel cdcajp = new OrderApprovalFromCdcJPanel(userProcessContainer,organization,enterprise,userAccount);
        userProcessContainer.add("CdcOrderApprovalJPanel", cdcajp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_orderApprovalJButtonActionPerformed

    private void PlaceOrderJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaceOrderJButtonActionPerformed
        // TODO add your handling code here:
        PlaceOrderToManufacuturerJPanel pojp = new PlaceOrderToManufacuturerJPanel(userProcessContainer,userAccount,enterprise,organization);
        userProcessContainer.add("PlaceOrderJPanel", pojp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_PlaceOrderJButtonActionPerformed

    private void paymentsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentsJButtonActionPerformed
        // TODO add your handling code here:
        PaymentToManufacturerJPanel pmjp = new PaymentToManufacturerJPanel(userProcessContainer,userAccount,organization);
        userProcessContainer.add("PaymentJP", pmjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_paymentsJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        BillToCdcJPanel bcdjp = new BillToCdcJPanel(userProcessContainer,userAccount,organization,network);
        userProcessContainer.add("BillToCdc", bcdjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PlaceOrderJButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageWarehouseJButton;
    private javax.swing.JButton orderApprovalJButton;
    private javax.swing.JButton paymentsJButton;
    // End of variables declaration//GEN-END:variables
}
