/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.hospitalRole;

import business.OrderItem;
import business.enterprise.Enterprise;
import business.organization.HospitalOrganization;
import business.userAccount.UserAccount;
import business.workQueue.VaccineRequest;
import business.workQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author Smeet
 */
public class VaccineApprovalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VaccineApprovalJPanel
     */
    JPanel userProcessContainer;
    HospitalOrganization parentOrg;
    UserAccount userAccount;
    Enterprise parentEnt;

    public VaccineApprovalJPanel(JPanel upc, HospitalOrganization parentOrg, UserAccount ua, Enterprise parentEnt) {
        initComponents();
        this.userProcessContainer = upc;
        this.parentOrg = parentOrg;
        this.userAccount = ua;
        this.parentEnt = parentEnt;
        // System.out.println(e.getName());

        populateTable();
    }

    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) vaccineApproveJTable.getModel();
        dtm.setRowCount(0);

        for (WorkRequest wr : parentOrg.getWorkQueue().getWorkRequestList()) {

            if (wr instanceof VaccineRequest) {

                VaccineRequest vr = (VaccineRequest) wr;
                if (!vr.getStatus().equals("Forwaded To PHD")) {
                    for (OrderItem oi : vr.getOrder().getOrderItemList()) {

                        Object row[] = new Object[5];
                        row[0] = vr;
                        row[1] = (vr.getSender() == null) ? ("N/A") : (vr.getSender().getEmployee().getName());
                        row[2] = vr.getStatus();
                        row[3] = oi.getQuantity();
                        row[4] = oi.getVaccine().getVacName();

                        dtm.addRow(row);
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        vaccineApproveJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        forwardToPHDJButton = new javax.swing.JButton();
        progressJProgressBar = new javax.swing.JProgressBar();

        setLayout(new java.awt.GridBagLayout());

        vaccineApproveJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Date", "Sender", "Status", "Quantity", "Vaccine Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(vaccineApproveJTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 384;
        gridBagConstraints.ipady = 70;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(54, 235, 0, 235);
        add(jScrollPane1, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel1.setText("  Vaccine Approval");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(51, 44, 0, 0);
        add(jLabel1, gridBagConstraints);

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 48;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(97, 182, 196, 0);
        add(backJButton, gridBagConstraints);

        forwardToPHDJButton.setText("Forward To PHD");
        forwardToPHDJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forwardToPHDJButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 254, 0, 0);
        add(forwardToPHDJButton, gridBagConstraints);

        progressJProgressBar.setStringPainted(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 195;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(103, 235, 0, 0);
        add(progressJProgressBar, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void forwardToPHDJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forwardToPHDJButtonActionPerformed
        // TODO add your handling code here:

        VaccineRequest vacReq;
        int selectedRow = vaccineApproveJTable.getSelectedRow();

        if (selectedRow >= 0) {
            vacReq = (VaccineRequest) vaccineApproveJTable.getValueAt(selectedRow, 0);
            // Integer oi = (Integer) vaccineApproveJTable.getValueAt(selectedRow, 3);
            vacReq.setStatus("Forwaded To PHD");
            vacReq.sethOrg(parentOrg);
            //vacReq.setQuantity(oi);
            //  for(OrderItem oi1: vacReq.getOrder().getOrderItemList()){
            //    vacReq.setVacName(oi1.getVaccine().getVacName());
            // }
            parentEnt.getWorkQueue().getWorkRequestList().add(vacReq);
            // System.out.println(vacReq);
            userAccount.getWorkQueue().getWorkRequestList().add(vacReq);
            
            progressJProgressBar.setValue(20);
            populateTable();
        }
    }//GEN-LAST:event_forwardToPHDJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton forwardToPHDJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JProgressBar progressJProgressBar;
    private javax.swing.JTable vaccineApproveJTable;
    // End of variables declaration//GEN-END:variables
}
