/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.hospitalRole;

import business.organization.Organization;
import business.userAccount.UserAccount;
import business.workQueue.PaymentRequest;
import business.workQueue.WorkRequest;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Smeet
 */
public class ViewPaymentsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPaymentsJPanel
     */
    
    JPanel userProcessContainer;
    UserAccount userAccount;
    Organization organization;
    public ViewPaymentsJPanel(JPanel upc,UserAccount ua,Organization o) {
        initComponents();
        this.userProcessContainer = upc;
        this.userAccount = ua;
        this.organization = o;
        populatePaymentTable();
    }
    
    private void populatePaymentTable(){
        DefaultTableModel dtm = (DefaultTableModel)viewPayementJTable.getModel();
        dtm.setRowCount(0);
        
        for(WorkRequest wr : organization.getWorkQueue().getWorkRequestList()){
            if(wr instanceof PaymentRequest){
                PaymentRequest pr = (PaymentRequest) wr;
                Object row[] = new Object[4];
                row[0] = pr;
                row[1] = pr.getSender();
                row[2] = pr.getStatus();
                dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewPayementJTable = new javax.swing.JTable();
        makePaymentJButton = new javax.swing.JButton();

        jLabel1.setText("View Payments");

        viewPayementJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Date", "Sender", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(viewPayementJTable);

        makePaymentJButton.setText("Make Payment");
        makePaymentJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makePaymentJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(361, 361, 361)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(makePaymentJButton)))
                .addContainerGap(228, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(makePaymentJButton)
                .addContainerGap(517, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void makePaymentJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makePaymentJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = viewPayementJTable.getSelectedRow();
        if(selectedRow<0){
            return;
        }
        PaymentRequest pr;
        
        pr = (PaymentRequest)viewPayementJTable.getValueAt(selectedRow, 0);
        pr.setStatus("Paid");
        populatePaymentTable();
    }//GEN-LAST:event_makePaymentJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton makePaymentJButton;
    private javax.swing.JTable viewPayementJTable;
    // End of variables declaration//GEN-END:variables
}
