/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.StateRole;

import business.OrderItem;
import business.enterprise.CdcEnterprise;
import business.enterprise.Enterprise;
import business.organization.DistributorOrganization;
import business.organization.Organization;
import business.userAccount.UserAccount;
import business.workQueue.VaccineRequest;
import business.workQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Smeet
 */
public class ApproveNewOrderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ApproveNewOrderJPanel
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    CdcEnterprise parentEnt;
    Enterprise enterprise;

    public ApproveNewOrderJPanel(JPanel upc, UserAccount ua, Enterprise e, CdcEnterprise parentEnt) {
        initComponents();
        this.userProcessContainer = upc;
        this.userAccount = ua;
        this.parentEnt = parentEnt;
        this.enterprise = e;
        //  System.out.println(e.getName());
        populateTable();

    }

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) vaccineApproveJTable.getModel();
        dtm.setRowCount(0);

        for (WorkRequest wr : enterprise.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof VaccineRequest) {

                VaccineRequest vr = (VaccineRequest) wr;
                if (!vr.getStatus().equals("Forwaded To CDC")) {
                    for (OrderItem oi : vr.getOrder().getOrderItemList()) {
                        Object row[] = new Object[6];
                        row[0] = vr;
                        row[1] = (vr.getSender() == null) ? ("N/A") : (vr.getSender().getEmployee().getName());
                        row[2] = vr.getStatus();
                        row[3] = oi.getQuantity();
                        row[4] = oi;
                        row[5] = oi.getVaccine().getVacName();
                        dtm.addRow(row);
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        approveVaccineJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vaccineApproveJTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();
        progressjProgressBar = new javax.swing.JProgressBar();

        setLayout(new java.awt.GridBagLayout());

        approveVaccineJButton.setText("Forward To CDC");
        approveVaccineJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveVaccineJButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 46;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(49, 199, 0, 0);
        add(approveVaccineJButton, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel1.setText("  Vaccine Approval");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(64, 73, 0, 0);
        add(jLabel1, gridBagConstraints);

        vaccineApproveJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Date", "Sender", "Status", "Quantity", "Vaccine Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(vaccineApproveJTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 536;
        gridBagConstraints.ipady = 70;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(51, 133, 0, 149);
        add(jScrollPane1, gridBagConstraints);

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(65, 165, 219, 0);
        add(backJButton, gridBagConstraints);

        progressjProgressBar.setStringPainted(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 182;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(99, 165, 0, 0);
        add(progressjProgressBar, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void approveVaccineJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveVaccineJButtonActionPerformed
        // TODO add your handling code here:
        VaccineRequest vacReq;
        int selectedRow = vaccineApproveJTable.getSelectedRow();
        if (selectedRow >= 0) {
            vacReq = (VaccineRequest) vaccineApproveJTable.getValueAt(selectedRow, 0);
            int oi = (Integer) vaccineApproveJTable.getValueAt(selectedRow, 3);
            //vacReq.setReceiver(userAccount);
            vacReq.setStatus("Forwaded To CDC");
            //vacReq.setRequestedVaccine("Vaccine Accepted");
           // vacReq.setSender(userAccount);
            vacReq.setQuantity(oi);
            populateTable();

            //Organization foundOrg = null;
           // for (Organization org : parentEnt.getOrganizationDirectory().getOrganizationList()) {
                //for (Organization o : org.getOrganizationDirectory().getOrganizationList()) {
                // if (o instanceof DistributorOrganization) {
                parentEnt.getWorkQueue().getWorkRequestList().add(vacReq);
                userAccount.getWorkQueue().getWorkRequestList().add(vacReq);
                progressjProgressBar.setValue(40);
                populateTable();

                //}
            

        }
    }//GEN-LAST:event_approveVaccineJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveVaccineJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JProgressBar progressjProgressBar;
    private javax.swing.JTable vaccineApproveJTable;
    // End of variables declaration//GEN-END:variables
}
